name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write
  attestations: write

env:
  PROJ_NAME: daphne

jobs:
  build:
    name: build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          # - windows-latest
        python-version:
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
            python-version: ${{ matrix.python-version }}

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Check black format
        if: success() || failure()
        run: uv run black . --check

      - name: Check ruff format
        if: success() || failure()
        run: uv run ruff format . --check

      - name: Run ruff check
        if: success() || failure()
        run: uv run ruff check --output-format=github .

      - name: Run type checks
        if: success() || failure()
        run: uv run mypy .

      - name: Run tests
        if: success() || failure()
        run: uv run pytest tests --cov=$PROJ_NAME --cov-report=html

      - name: Build wheel
        if: success() || failure()
        run: uv build

      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: coverage_html_report/code-coverage.html

      - name: Upload wheel artifact
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: ${{ vars.PROJ_NAME }}-wheel
          path: dist/*.whl

      - name: Upload source distribution artifact
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: ${{ vars.PROJ_NAME }}-sdist
          path: dist/*.tar.gz
