name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    name: build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu
          # - windows
        python-version:
          - "3.9"
          # - "3.10"
          # - "3.11"
          # - "3.12"
          # - "3.13"

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
            python-version: ${{ matrix.python-version }}

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Check black format
        if: success() || failure()
        run: uv run black --check
        # run: ruff format --check

      - name: Check ruff format
        if: success() || failure()
        run: ruff format --check

      - name: Run flake8
        if: success() || failure()
        run: uv run flake8 .

      - name: Run ruff check
        if: success() || failure()
        run: uv run ruff check --output-format=github .

      - name: Run tests
        if: success() || failure()
        run: uv run pytest tests

      - name: Build wheel
        if: success() || failure()
        run: uv build

      # - name: Archive code coverage results
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: code-coverage-report
      #     path: output/test/code-coverage.html

      - name: Upload wheel artifact
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: daphne-wheel
          path: dist/*.whl
